project/administracion/urls.py
from django.urls import path
from .views import administracion, HorasView, GastosView, PagosView, UsuariosView, Cargar_usuarios

app_name = 'administracion'

urlpatterns = [
    path('', administracion, name='administracion'),
    path('gastos/', GastosView.as_view(), name='gastos'),
    path('horas/', HorasView.as_view(), name='horas'),
    path('pagos/', PagosView.as_view(), name='pagos'),
    path('usuarios/', UsuariosView.as_view(), name='usuarios'),
    path('cargar_usuario/', Cargar_usuarios.as_view(), name='cargar_usuarios')
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin-kinef-2025/', admin.site.urls),
    path('', include('core.urls')),
    path('administracion/', include('administracion.urls')),
    path('usuarios/', include('usuarios.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.urls import path
from .views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

project/usuarios/urls.py
from django.urls import path
from .views import UserManagementView, PerfilView
from django.contrib.auth.views import LogoutView

app_name = 'usuarios'

urlpatterns = [
    path('user-management/', UserManagementView.as_view(), name='user_management'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('perfil/', PerfilView.as_view(), name='perfil'),
]

project/administracion/views.py
from django.shortcuts import render
from django.views import View
from django.http import JsonResponse
from usuarios.models import Usuarios, validate_image
from .models import Horas, Gastos, Pagos
from datetime import datetime
from django.utils.timezone import now
import json
from django.contrib.auth.models import User
from django.forms import ValidationError


def administracion(request):
    return render(request, 'administracion/administracion.html')

class HorasView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'administracion/horas.html')

    def post(self, request):
        try:
            data = json.loads(request.body)
            action = data.get('action')

            if action == 'cargar':
                return self.carga_horas(data)
            elif action == 'obtener_usuarios':
                return self.obtener_usuarios()
            elif action == 'obtener_horas':
                return self.obtener_horas()
            elif action == 'sumar_horas':
                return self.horas_este_mes()
            else:
                return JsonResponse({'error': 'Se produjo un error'}, status=400)
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Formato incorrecto'}, status=400)

    def carga_horas(self, data):
        try:
            usuario_id = data.get('usuario')
            dia = data.get('dia')
            horas = data.get('horas')

            usuario = Usuarios.objects.get(id=usuario_id)

            Horas.objects.create(usuario=usuario, dia=dia, horas=horas)

            return JsonResponse({'success': 'Horas cargadas correctamente'})
        except Usuarios.DoesNotExist:
            return JsonResponse({'error': 'Usuario no encontrado'}, status=404)
        except Exception:
            return JsonResponse({'error': 'Error interno del servidor'}, status=500)

    def obtener_usuarios(self):
        try:
            usuarios = Usuarios.objects.filter(user__is_superuser=True).values('id', 'user__username')
            return JsonResponse(list(usuarios), safe=False)
        except Exception:
            return JsonResponse({'error': 'Error al obtener usuarios'}, status=500)

    def obtener_horas(self):
        try:
            horas = Horas.objects.select_related('usuario').all().values(
                'id', 'usuario__user__username', 'dia', 'horas'
            )
            data = []
            for hora in horas:
                hora['dia'] = hora['dia'].strftime('%Y/%m/%d') 
                data.append(hora)
            return JsonResponse(data, safe=False)
        except Exception:
            return JsonResponse({'error': 'Error al obtener las horas'}, status=500)

    def horas_este_mes(self):
        try:
            # Obtener el mes y año actuales
            fecha_actual = now()
            mes_actual = fecha_actual.month
            año_actual = fecha_actual.year

            # Filtrar las horas del mes y año actuales
            horas = Horas.objects.filter(dia__year=año_actual, dia__month=mes_actual).select_related('usuario').values(
                'id', 'usuario__user__username', 'dia', 'horas'
            )

            data = []
            for hora in horas:
                hora['dia'] = hora['dia'].strftime('%Y-%m-%d')  # Formatear la fecha para JSON
                data.append(hora)

            return JsonResponse(data, safe=False)
        except Exception:
            return JsonResponse({'error': 'Error al obtener las horas del mes'}, status=500)

class GastosView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'administracion/gastos.html')

    def post(self, request):
        try:
            data = json.loads(request.body)
            action = data.get('action')

            if action == 'cargar':
                return self.carga_gastos(data)
            elif action == 'obtener_usuarios':
                return self.obtener_usuarios()
            elif action == 'obtener_gastos':
                return self.obtener_gastos()
            else:
                return JsonResponse({'error': 'Se produjo un error'}, status=400)
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Formato incorrecto'}, status=400)

    def carga_gastos(self, data):
        try:
            usuario_id = data.get('usuario')
            concepto = data.get('concepto')
            monto = float(data.get('monto', 0))
            fecha_gasto = datetime.strptime(data.get('fecha_gasto'), '%Y-%m-%d').date()

            usuario = Usuarios.objects.get(id=usuario_id)
            if not concepto or len(concepto) > 200:
                return JsonResponse({'error': 'El concepto es inválido'}, status=400)
            if not isinstance(monto, (float, int)) or monto <= 0:
                return JsonResponse({'error': 'El monto es inválido'}, status=400)

            Gastos.objects.create(usuario=usuario, concepto=concepto, monto=monto, fecha_gasto=fecha_gasto)
            return JsonResponse({'success': 'Gasto cargado correctamente'})
        except Usuarios.DoesNotExist:
            return JsonResponse({'error': 'Usuario no encontrado'}, status=404)
        except Exception:
            return JsonResponse({'error': 'Error al cargar'}, status=400)

    def obtener_usuarios(self):
        try:
            usuarios = Usuarios.objects.filter(user__is_superuser=True).values('id', 'user__username')
            return JsonResponse(list(usuarios), safe=False)
        except Exception:
            return JsonResponse({'error': 'Error al obtener usuarios'}, status=500)

    def obtener_gastos(self):
        try:
            gastos = Gastos.objects.select_related('usuario').all().values(
                'usuario__user__username', 'concepto', 'monto', 'fecha_gasto'
            )
            data = []
            for gasto in gastos:
                gasto['fecha_gasto'] = gasto['fecha_gasto'].strftime('%d/%m/%Y') 
                data.append(gasto)
            return JsonResponse(data, safe=False)
        except Exception:
            return JsonResponse({'error': 'Error al obtener las horas'}, status=500)

class PagosView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'administracion/pagos.html')

    def post(self, request):
        try:
            data = json.loads(request.body)
            action = data.get('action')

            if action == 'cargar':
                return self.carga_pagos(data)
            elif action == 'obtener_usuarios':
                return self.obtener_usuarios()
            elif action == 'obtener_pagos':
                return self.obtener_pagos()
            else:
                return JsonResponse({'error': 'Se produjo un error'}, status=400)
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Formato incorrecto'}, status=400)

    def carga_pagos(self, data):
        try:
            usuario_id = data.get('usuario')
            monto = data.get('monto')
            modo_pago = data.get('modo_pago')
            actividad = data.get('actividad')
            pase = data.get('pase')
            fecha = data.get('fecha')

            usuario = Usuarios.objects.get(id=usuario_id)

            Pagos.objects.create(usuario=usuario, monto=monto, modo_pago=modo_pago, actividad=actividad, pase=pase, fecha=fecha)
            return JsonResponse({'success': 'Pago cargado correctamente'})
        except Usuarios.DoesNotExist:
            return JsonResponse({'error': 'Usuario no encontrado'}, status=404)
        except Exception:
            return JsonResponse({'error': 'Error al cargar'}, status=400)

    def obtener_usuarios(self):
        try:
            usuarios = Usuarios.objects.filter().values('id', 'user__username', 'dni')
            return JsonResponse(list(usuarios), safe=False)
        except Exception:
            return JsonResponse({'error': 'Error al obtener usuarios'}, status=500)

    def obtener_pagos(self):
        try:
            pagos = Pagos.objects.select_related('usuario').all().values(
                'usuario__user__username', 'monto', 'modo_pago', 'actividad', 'pase', 'fecha'
            )

            data = []
            for pago in pagos:
                pago['fecha'] = pago['fecha'].strftime('%d/%m/%Y') 
                data.append(pago)
            return JsonResponse(data, safe=False)
        except Exception:
            return JsonResponse({'error': 'Error al obtener los pagos'}, status=500)

class UsuariosView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'administracion/usuarios.html')

    def post(self,request):
        try:
            data = json.loads(request.body)
            action = data.get('action')

            if action == 'obtener_usuarios':
                return self.obtener_usuarios()
            else:
                return JsonResponse({'error': 'Se produjo un error'}, status=400)

        except json.JSONDecodeError:
            return JsonResponse({'error': 'Formato incorrecto'}, status=400)

    def obtener_usuarios(self):
        try:
            usuarios = Usuarios.objects.all()
            usuarios_data = [
                {
                    'user__username': usuario.user.username,
                    'nombre': usuario.nombre,
                    'apellido': usuario.apellido,
                    'mail': usuario.mail if usuario.mail else '-',
                    'dni': usuario.dni,
                    'telefono': usuario.telefono,
                    'domicilio': usuario.domicilio,
                    'fecha_nacimiento': usuario.fecha_nacimiento.strftime('%d/%m/%Y') if usuario.fecha_nacimiento else None,
                    'instagram': usuario.instagram if usuario.instagram else '-',
                    'foto': usuario.foto.url if usuario.foto else None,
                    'cargado': usuario.cargado.strftime('%d/%m/%Y') if usuario.cargado else None,
                }

project/usuarios/views.py
import json
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.views import View
from .models import Usuarios, validate_image
from django.forms import ValidationError

class UserManagementView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'usuarios/user-management.html')

    def post(self, request):
        try:
            if request.content_type == 'application/json':
                data = json.loads(request.body)
                action = data.get('action')
            else:
                action = request.POST.get('action')

            if action == 'register':
                return self.register_user(request)
            elif action == 'login':
                return self.login_user(request, data)
            else:
                return JsonResponse({'error': 'Acción no válida'}, status=400)
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Formato de solicitud inválido'}, status=400)

    def register_user(self, request):
        try:
            username = request.POST.get('username')
            password = request.POST.get('password')
            nombre = request.POST.get('nombre')
            apellido = request.POST.get('apellido')
            mail = request.POST.get('mail')
            dni = request.POST.get('dni')
            fecha_nacimiento = request.POST.get('fecha_nacimiento')
            telefono = request.POST.get('telefono')
            domicilio = request.POST.get('domicilio')
            instagram = request.POST.get('instagram')
            foto = request.FILES.get('foto')

            if User.objects.filter(username=username).exists():
                return JsonResponse({'error': 'El usuario ya existe'}, status=400)

            if Usuarios.objects.filter(dni=dni).exists():
                return JsonResponse({'error': 'El DNI ya está cargado'}, status=400)

            if not dni or len(dni) != 8 or not dni.isdigit():
                return JsonResponse({'error': 'El DNI debe tener 8 dígitos numéricos'}, status=400)

            if foto:
                try:
                    validate_image(foto)
                except ValidationError as e:
                    return JsonResponse({'error': str(e)}, status=400)

            user = User.objects.create_user(username=username, password=password)
            Usuarios.objects.create(
                user=user,
                nombre=nombre,
                apellido=apellido,
                mail=mail,
                dni=dni,
                fecha_nacimiento=fecha_nacimiento,
                telefono=telefono,
                domicilio=domicilio,
                instagram=instagram,
                foto=foto
            )
            return JsonResponse({'success': f'{username} se ha registrado con éxito'})
        except Exception:
            return JsonResponse({'error': 'Error al intentar registrar, verifique los datos'}, status=500)

    def login_user(self, request, data):
        try:
            username = data.get('username')
            password = data.get('password')

            if not username or not password:
                return JsonResponse({'error': 'Usuario y contraseña son requeridos'}, status=400)

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return JsonResponse({'success': f'{username} ha iniciado sesión'})
            else:
                return JsonResponse({'error': 'Usuario o contraseña incorrectos'}, status=401)
        except Exception:
            return JsonResponse({'error': 'Error interno del servidor al iniciar sesión'}, status=500)

class PerfilView(View):
    def get(self, request, *args, **kwargs):
        usuario_actual = request.user.usuarios

        contexto = {
            'username': usuario_actual.user.username,
            'nombre': usuario_actual.nombre,
            'apellido': usuario_actual.apellido,
            'mail': usuario_actual.mail,
            'foto': usuario_actual.foto,
            'dni': usuario_actual.dni,
            'fecha_nacimiento' : usuario_actual.fecha_nacimiento,
            'telefono' : usuario_actual.telefono,
            'domicilio': usuario_actual.domicilio,
            'instagram' : usuario_actual.instagram,
            'cargado' : usuario_actual.cargado,
        }
        return render(request, 'usuarios/perfil.html', contexto)

    def post(self, request):
        try:
            data = json.loads(request.body)
            action = data.get('action')

            if action == 'obtener_usuarios':
                return self.obtener_usuarios()
            else:
                return JsonResponse({'error': 'Error inesperado'}, status=400)
        except Exception:
            return JsonResponse({'error': 'Error al cargar la peticion'}, status=400)

    def obtener_usuarios(self):
        try:
            usuarios = Usuarios.objects.filter().values('user__username', 'foto')
            return JsonResponse(list(usuarios), safe=False)
        except Exception:
            return JsonResponse({'error': 'Error al obtener usuarios'}, status=500)

project/administracion/templates/administracion/administracion.html
{% extends 'core/base.html' %}

{% block title %}
    Administración
{% endblock title %}

{% block content %}
    <div class="administracion-main">
        <h1>Administración</h1>
        <ul>
            <a href="{% url 'administracion:horas' %}" class="boton-basico">Horas</a>
            <a href="{% url 'administracion:gastos' %}" class="boton-basico">Gastos</a>
            <a href="{% url 'administracion:pagos' %}" class="boton-basico">Pagos</a>
            <a href="{% url 'administracion:usuarios' %}" class="boton-basico">Usuarios</a>
            <a href="{% url 'administracion:cargar_usuarios' %}" class="boton-basico">Cargar Usuario</a>
        </ul>
    </div>
{% endblock content %}

project/administracion/templates/administracion/cargar_usuarios.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'img/kinef_logo1.png' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Usuarios</title>
</head>
<body>
    <nav class="navbar">
        {% include 'core/components/navbar.html' %}
    </nav>
    <main class="contenedor-main">
        <div class="administracion-main">
            <h1>Administración</h1>
            <ul>
                <a href="{% url 'administracion:horas' %}" class="boton-basico">Horas</a>
                <a href="{% url 'administracion:gastos' %}" class="boton-basico">Gastos</a>
                <a href="{% url 'administracion:pagos' %}" class="boton-basico">Pagos</a>
                <a href="{% url 'administracion:usuarios' %}" class="boton-basico">Usuarios</a>
                <a href="{% url 'administracion:cargar_usuarios' %}" class="boton-basico">Cargar Usuario</a>
            </ul>
        </div>
        <div class="usuarios-main">
            <h2>Cargar usuario</h2>
            <div id="errores_password"></div>
            <form id="register-form" enctype="multipart/form-data" class="form-cargar-usuario">
                {% csrf_token %}
                <input type="text" name="username" placeholder="Nombre de Usuario" required />
                <input type="password" name="password" placeholder="Contraseña" id="password" required />
                <input type="password" name="password2" placeholder="Repite la contraseña" id="password2" required />
                <input type="text" name="nombre" placeholder="Nombre" required>
                <input type="text" name="apellido" placeholder="Apellido" required>
                <input type="date" name="fecha_nacimiento" required />
                <input type="text" name="dni" placeholder="DNI" required />
                <input type="text" name="telefono" placeholder="Teléfono"/>
                <input type="email" name="mail" placeholder="Mail">
                <input type="text" name="domicilio" placeholder="Domicilio"/>
                <input type="text" name="instagram" placeholder="Instagram" />
                <input type="file" name="foto">
                <button type="submit" class="boton-login">Registrar</button>
            </form>
        </div>
        <div class="boton-atras-contenedor">
            <a href="{% url 'administracion:administracion' %}" class="boton-basico"><strong>←</strong></a>
        </div>
    </main>
    <footer class="footer">
        {% include 'core/components/footer.html' %}
    </footer>


    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="{% static 'administracion/scripts/cargar-usuarios.js' %}"></script>
</body>
</html>

project/administracion/templates/administracion/gastos.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'img/kinef_logo1.png' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Gastos</title>
</head>
<body>
    <nav class="navbar">
        {% include 'core/components/navbar.html' %}
    </nav>
    <main class="contenedor-main">
        <div class="administracion-main">
            <h1>Administración</h1>
            <ul>
                <a href="{% url 'administracion:horas' %}" class="boton-basico">Horas</a>
                <a href="{% url 'administracion:gastos' %}" class="boton-basico">Gastos</a>
                <a href="{% url 'administracion:pagos' %}" class="boton-basico">Pagos</a>
                <a href="{% url 'administracion:usuarios' %}" class="boton-basico">Usuarios</a>
                <a href="{% url 'administracion:cargar_usuarios' %}" class="boton-basico">Cargar Usuario</a>
            </ul>
        </div>
        <div class="horas-main">
            <h2>Gastos</h2>
            <div class="form-contenedor">
                <button class="boton-basico" id="cargar_gastos">Cargar Gasto</button>
                <form id="gastos_form" class="gastos-form">
                    {% csrf_token %}
                    <select name="usuario" id="usuario">
                        <option value="">Usuario que carga</option>
                    </select>
                    <input type="text" name="concepto" maxlength="200" placeholder="Concepto" required>
                    <input type="" name="monto" placeholder="Monto" min="0" step="0,001" required>
                    <label for="fecha_gasto">Fecha del gasto</label>
                    <input type="date" name="fecha_gasto" id="fecha_gasto" required>
                    <button type="submit" class="boton-cargar">Cargar Gasto</button>
                </form>
            </div>
            <input type="search" id="buscar_gasto" class="buscar-usuario" placeholder="Buscar Gasto">
        </div>
        <div class="contenedor-gastos">
            <div id="gastos_cargados" class="gastos-cargados"></div>
        </div>
        <div class="boton-atras-contenedor">
            <a href="{% url 'administracion:administracion' %}" class="boton-basico"><strong>←</strong></a>
        </div>
    </main>
    <footer class="footer">
        {% include 'core/components/footer.html' %}
    </footer>


    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="{% static 'administracion/scripts/gastos.js' %}"></script>
</body>
</html>

project/administracion/templates/administracion/horas.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'img/kinef_logo1.png' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Horas</title>
</head>
<body>
    <nav class="navbar">
        {% include 'core/components/navbar.html' %}
    </nav>
    <main class="contenedor-main">
        <div class="administracion-main">
            <h1>Administración</h1>
            <ul>
                <a href="{% url 'administracion:horas' %}" class="boton-basico">Horas</a>
                <a href="{% url 'administracion:gastos' %}" class="boton-basico">Gastos</a>
                <a href="{% url 'administracion:pagos' %}" class="boton-basico">Pagos</a>
                <a href="{% url 'administracion:usuarios' %}" class="boton-basico">Usuarios</a>
            </ul>
        </div>
        <div class="horas-main">
            <h2>Horas</h2>
            <div class="form-horas-contenedor">
                <button class="boton-basico" id="cargar_horas">Cargar horas</button>
                <form id="horas_form" class="horas-form">
                    {% csrf_token %}
                    <select name="usuario" id="usuario">
                        <option value="">Usuario</option>
                    </select>
                    <input type="date" name="dia" required>
                    <input type="number" name="horas" maxlength="3" placeholder="Horas" required>
                    <button type="submit" class="boton-cargar" id="boton_cargar">Cargar</button>
                </form>
            </div>
        </div>
        <div class="horas-cargadas-contenedor">
            <div class="botones-horas">
                <button id="mostrar_horas" class="boton-basico">Mostrar historial de horas</button>
                <button id="mostrar_horas_sumadas" class="boton-basico">Ver horas este mes</button>
            </div>
            <div id="horas_cargadas" class="horas-cargadas"></div>
            <div id="horas_sumadas" class="horas-cargadas"></div>
        </div>
        <div class="boton-atras-contenedor">
            <a href="{% url 'administracion:administracion' %}" class="boton-basico"><strong>←</strong></a>
        </div>
    </main>
    <footer class="footer">
        {% include 'core/components/footer.html' %}
    </footer>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="{% static 'administracion/scripts/horas.js' %}"></script>
</body>
</html>

project/administracion/templates/administracion/pagos.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'img/kinef_logo1.png' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Pagos</title>
</head>
<body>
    <nav class="navbar">
        {% include 'core/components/navbar.html' %}
    </nav>
    <main class="contenedor-main">
        <div class="administracion-main">
            <h1>Administración</h1>
            <ul>
                <a href="{% url 'administracion:horas' %}" class="boton-basico">Horas</a>
                <a href="{% url 'administracion:gastos' %}" class="boton-basico">Gastos</a>
                <a href="{% url 'administracion:pagos' %}" class="boton-basico">Pagos</a>
                <a href="{% url 'administracion:usuarios' %}" class="boton-basico">Usuarios</a>
                <a href="{% url 'administracion:cargar_usuarios' %}" class="boton-basico">Cargar Usuario</a>
            </ul>
        </div>
        <div class="horas-main">
            <h2>Pagos</h2>
            <div class="form-contenedor">
                <button class="boton-basico" id="cargar_pagos">Cargar Pago</button>
                <form id="pagos_form" class="gastos-form">
                    {% csrf_token %}
                    <select name="usuario" id="usuario">
                        <option value="">Usuario</option>
                    </select>
                    <input type="number" name="monto" placeholder="Monto" required>
                    <input type="text" name="modo_pago" maxlength="50" placeholder="Modo de pago" required>
                    <input type="text" name="actividad" maxlength="50" placeholder="Actividad" required>
                    <input type="text" name="pase" maxlength="50" placeholder="Tipo de Pase" required>
                    <input type="date" name="fecha" placeholder="Fecha" required>
                    <button type="submit" class="boton-cargar">Cargar Pago</button>
                </form>
            </div>
            <input type="search" id="buscar_pago" class="buscar-usuario" placeholder="Buscar Pago">
        </div>
        <div class="contenedor-gastos">
            <div id="pagos_cargados-activos" class="gastos-cargados"></div>
            <div id="pagos_cargados" class="gastos-cargados"></div>
        </div>
        <div class="boton-atras-contenedor">
            <a href="{% url 'administracion:administracion' %}" class="boton-basico"><strong>←</strong></a>
        </div>
    </main>
    <footer class="footer">
        {% include 'core/components/footer.html' %}
    </footer>


    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="{% static 'administracion/scripts/pagos.js' %}"></script>
</body>
</html>

project/administracion/templates/administracion/usuarios.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'img/kinef_logo1.png' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Usuarios</title>
</head>
<body>
    <nav class="navbar">
        {% include 'core/components/navbar.html' %}
    </nav>
    <main class="contenedor-main">
        <div class="administracion-main">
            <h1>Administración</h1>
            <ul>
                <a href="{% url 'administracion:horas' %}" class="boton-basico">Horas</a>
                <a href="{% url 'administracion:gastos' %}" class="boton-basico">Gastos</a>
                <a href="{% url 'administracion:pagos' %}" class="boton-basico">Pagos</a>
                <a href="{% url 'administracion:usuarios' %}" class="boton-basico">Usuarios</a>
                <a href="{% url 'administracion:cargar_usuarios' %}" class="boton-basico">Cargar Usuario</a>
            </ul>
        </div>
        <div class="usuarios-main">
            <h2>Usuarios</h2>
            <input type="search" id="buscar_usuario" class="buscar-usuario" placeholder="Buscar usuario">
            <div id="usuarios_cargados" class="usuarios-cargados"></div>
        </div>
        <div class="boton-atras-contenedor">
            <a href="{% url 'administracion:administracion' %}" class="boton-basico"><strong>←</strong></a>
        </div>
    </main>
    <footer class="footer">
        {% include 'core/components/footer.html' %}
    </footer>


    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="{% static 'administracion/scripts/usuarios.js' %}"></script>
</body>
</html>