project/administracion/urls.py
from django.urls import path
from .views import administracion, HorasView, GastosView, PagosView, UsuariosView, Cargar_usuarios

app_name = 'administracion'

urlpatterns = [
    path('', administracion, name='administracion'),
    path('gastos/', GastosView.as_view(), name='gastos'),
    path('horas/', HorasView.as_view(), name='horas'),
    path('pagos/', PagosView.as_view(), name='pagos'),
    path('usuarios/', UsuariosView.as_view(), name='usuarios'),
    path('cargar_usuario/', Cargar_usuarios.as_view(), name='cargar_usuarios')
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin-kinef-2025/', admin.site.urls),
    path('', include('core.urls')),
    path('administracion/', include('administracion.urls')),
    path('usuarios/', include('usuarios.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/urls.py
from django.urls import path
from .views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

project/usuarios/urls.py
from django.urls import path
from .views import UserManagementView, PerfilView
from django.contrib.auth.views import LogoutView

app_name = 'usuarios'

urlpatterns = [
    path('user-management/', UserManagementView.as_view(), name='user_management'),
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout'),
    path('perfil/', PerfilView.as_view(), name='perfil'),
]

project/core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'core/index.html')

project/core/templates/core/components/footer.html
{% load static %}
<div class="logo-kinef-contenedor">
    <a href="{% url 'core:index' %}"><img src="{% static 'img/kinef_logo.png' %}" alt="Logo de Kinef" class="logo-kinef"></a>
    <h5>Contacto: 351...</h5>
    <a href="{% url 'core:index' %}"><img src="{% static 'img/kinef_logo.png' %}" alt="Logo de Kinef" class="logo-kinef"></a>
</div>

project/core/templates/core/components/navbar.html
<a href="{% url 'core:index' %}" class="boton-basico">Inicio Kinef</a>
{% if user.is_superuser %}
    <a href="{% url 'administracion:administracion' %}" class="boton-basico">Administración</a>
{% endif %}
{% if user.is_authenticated %}
    <!-- <a href="{% url 'usuarios:perfil' %}" class="boton-basico">{{ user.username }}</a> -->
    {% if user.usuarios.foto %}
        <div class="foto-link-contenedor">
            <a href="{% url 'usuarios:perfil' %}"><img src="{{ user.usuarios.foto.url }}" alt="Perfil" class="foto-perfil"></a>
        </div>
    {% else %}
        <div class="foto-link-contenedor">
            <a href="{% url 'usuarios:perfil' %}"><img src="../../../static/img/kinef_logo1.png" alt="Logo de Kinef" class='foto-perfil'></a>
        </div>
    {% endif %}
    <form action="{% url 'usuarios:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="link boton-basico">Cerrar sesión</button>
    </form>
{% else %}
    <a href="{% url 'usuarios:user_management' %}" class="boton-basico">Iniciar sesión/Registrarse </a>
{% endif %}